knp_snappy:
  pdf:
    enabled: true
    binary: "C:/wkhtmltopdf/bin/wkhtmltopdf.exe"
    options:
      page-size: A4
      margin-top: 10mm
      margin-right: 10mm
      margin-bottom: 10mm
      margin-left: 10mm
# knp_snappy:
#   pdf:
#     enabled: true
#     binary: "C:\wkhtmltopdf"
#     options: []
# image:
#     enabled:    true
#     binary:     '%env(WKHTMLTOIMAGE_PATH)%'
#     options:    []

# temporary_folder: "%kernel.cache_dir%/snappy"
